### ISSUE TITLE
"SYSY-MM01/exp/rand_perm_cam.mat"  FileNotFoundError

### ISSUE THREAD

**Issue by hfutzzw** [LuckyDC/RGB-IR-ReID-Baseline#1]
"SYSY-MM01/exp/rand_perm_cam.mat" 
FileNotFoundError

**Comment by LuckyDC** [comment]
Download it from official SYSU-MM01 repo:
https://github.com/wuancong/SYSU-MM01/blob/master/evaluation/data_split/rand_perm_cam.mat
