### ISSUE TITLE
assert os.path.isdir(root) AssertionError

### ISSUE THREAD

**Issue by zhaoqiguo** [LuckyDC/RGB-IR-ReID-Baseline#2]
Hello, LuckyDC
When I run train.py as your readme mentioned. The AssertionError is raised both in softmax and softmax-triplet loss:
CUDA_VISIBLE_DEVICES=0 python3 train.py --cfg configs/softmax-triplet.yml
{'batch_size': 128,
 'classification': True,
 'color_jitter': False,
 'data_root': '/home/chuanchen_luo/data/SYSU',
 'dataset': 'sysu',
 'drop_last_stride': True,
 'dual_path': False,
 'eval_interval': 50,
 'fp16': True,
 'image_size': (256, 128),
 'k_size': 8,
 'log_period': 10,
 'lr': 0.00035,
 'lr_step': [150],
 'num_cam': 6,
 'num_epoch': 200,
 'num_id': 395,
 'optimizer': 'adam',
 'p_size': 16,
 'padding': 10,
 'prefix': 'sysu-nodual-adam-16x8-128',
 'random_crop': True,
 'random_erase': True,
 'random_flip': True,
 'sample_method': 'identity_uniform',
 'triplet': True,
 'wd': 0.0005}
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    train(cfg)
  File "train.py", line 46, in train
    num_workers=8)
  File "/media/zbx01/0cdb9b67-bb97-4984-b104-f1bbe012e4fd/guozhaoqi/Gitcode/RGB-IR-ReID-Baseline-master/data/__init__.py", line 42, in get_train_loader
    train_dataset = SYSUDataset(root, mode='train', transform=transform)
  File "/media/zbx01/0cdb9b67-bb97-4984-b104-f1bbe012e4fd/guozhaoqi/Gitcode/RGB-IR-ReID-Baseline-master/data/dataset.py", line 15, in __init__
    assert os.path.isdir(root)
AssertionError
My torch vision is 1.3.1, python vision is 3.7.4, cuda vision is 9.0
How could I fix it? Thx

**Comment by LuckyDC** [comment]
*.yml in ./configs directory define the setting of the experiment. In this case, you should append `data_root` entry to the file to override the default setting. That is, append `data_root: YOUR_DATASET_PATH` to `configs/softmax-triplet.yml` or `configs/softmax.yml`, where YOUR_DATASET_PATH denotes the path of the dataset in your computer
