### ISSUE TITLE
How to check the saved checkpoints

### ISSUE THREAD

**Issue by chaitrasj** [LuckyDC/RGB-IR-ReID-Baseline#4]
Thanks a lot for open sourcing this awesome work.
I had a query regarding the saved checkpoints. When I run the model, during the initial epochs itself it creates 3 checkpoints. As per the code, it should save the model after 10 epochs, however, which checkpoints get created at the start of training?
Also, the naming of checkpoint created is a bit confusing, I couldn't clearly understand what the suffix means, I tried to read through the Ignite documentation but they say some scoring value which I couldn't understand what is, can you please throw some light on this?
Also, all the 3 checkpoints when tested give same mAP and cmc values at the end of training. Aren't they the models saved after 10th, 20th and 30th epoch? If so they should have varying accuracies as seen during the training?
Please correct me if I am wrong
Thank you

**Comment by LuckyDC** [comment]
This repo use ignite 0.2.0. As stated in its doc:
> Each filename has the following structure: {filename_prefix}_{name}_{step_number}.pth. Here, filename_prefix is the argument passed to the constructor, name is the key in the aforementioned dict, and step_number is incremented by 1 with every call to the handler.

The model is saved at the end of each epoch and only keep the n_saved=3 latest checkpoints. You may be confused about the following code:
```python
if epoch % eval_interval == 0:
    logger.info("Model saved at {}/{}_model_{}.pth".format(save_dir, prefix, epoch))
```
This is only used to remind me that evaluation is performed on this checkpoint. You can delete this line safely.

**Comment by chaitrasj** [comment]
That helps. Thanks a lot!

**Comment by chaitrasj** [comment]
Hi @LuckyDC ,
If it's saving the latest 3 checkpoints always, it might happen that at the 10th epoch the accuracy was better than the 20th epoch, but the 10th epoch model got overwritten by the latest 3 models, is this possible?
Also if the name of the checkpoint stored is based on the number of times the handler is called, then are the previously-stored models simply deleted and a new model with the name based on the current handler call number is simply getting stored at the end of each epoch?
